-- =========================================
-- Inserts for table: meta
-- Description: Meta information for each page
-- =========================================

-- First, clear the meta table
TRUNCATE TABLE `meta`;

INSERT INTO `meta` 
(`meta_id`, `page_id`, `title`, `description`, `og_url`, `og_image`, `twitter_image`, `css`, `created_at`, `updated_at`) 
VALUES
(1,  1, 'Mirnes Glamočić | Expert Web Developer and Web Designer', 
      'Professional website development, UI/UX and web design services by certified IT expert from Bosnia and Herzegovina.  The best of the best!', 
      'https://mirnesglamocic.com', 
      'https://mirnesglamocic.com/images/og_img/mirnes_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/mirnes_og.webp', 
      'css.min.php', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(2,  2, 'Frontend Certificates of IT expert Mirnes Glamočić', 
      'See the Frontend certificates of professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/front-end-certificates', 
      'https://mirnesglamocic.com/images/og_img/frontend_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/frontend_og.webp', 
      'certificates.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(3,  3, 'Back-end certificates of IT expert Mirnes Glamočić', 
      'See the Back-end certificates of professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/back-end-certificates', 
      'https://mirnesglamocic.com/images/og_img/backend_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/backend_og.webp', 
      'certificates.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(4,  4, 'Database certificates of IT expert Mirnes Glamočić', 
      'See the Database certificates of professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/database-certificates', 
      'https://mirnesglamocic.com/images/og_img/database_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/database_og.webp', 
      'certificates.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(5,  5, 'WordPress certificates of IT expert Mirnes Glamočić', 
      'See the WordPress certificates of professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/wordpress-certificates', 
      'https://mirnesglamocic.com/images/og_img/wordpress_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/wordpress_og.webp', 
      'certificates.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(6,  6, 'Web Services certificates of IT expert Mirnes Glamočić', 
      'See the Web Services certificates of professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/web-services-certificates', 
      'https://mirnesglamocic.com/images/og_img/webservices_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/webservices_og.webp', 
      'certificates.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(7,  7, 'Web Design Certificates of IT expert Mirnes Glamočić', 
      'See the Web Design certificates of professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/web-design-certificates', 
      'https://mirnesglamocic.com/images/og_img/webdesign_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/webdesign_og.webp', 
      'certificates.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(8,  8, 'UI/UX certificates of IT expert Mirnes Glamočić', 
      'See the UI/UX certificates of professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/ui-ux-design-certificates', 
      'https://mirnesglamocic.com/images/og_img/ux_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/ux_og.webp', 
      'certificates.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(9,  9, 'SEO certificates of IT expert Mirnes Glamočić', 
      'See the SEO certificates of professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/seo-certificates', 
      'https://mirnesglamocic.com/images/og_img/seo_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/seo_og.webp', 
      'certificates.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(10, 10, 'Adobe CC certificates of IT expert Mirnes Glamočić', 
      'See the Adobe CC certificates of professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/adobe-cc-certificates', 
      'https://mirnesglamocic.com/images/og_img/adobe_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/adobe_og.webp', 
      'certificates.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(11, 11, 'Version Control certificates of IT expert Mirnes Glamočić', 
      'See the Version Control certificates of professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/version-control-certificates', 
      'https://mirnesglamocic.com/images/og_img/git_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/git_og.webp', 
      'certificates.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(12, 12, 'Docker certificates of IT expert Mirnes Glamočić', 
      'See the Docker certificates of professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/docker-certificates', 
      'https://mirnesglamocic.com/images/og_img/docker-og.jpg', 
      'https://mirnesglamocic.com/images/og_img/docker-og.webp', 
      'certificates.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(13, 13, 'Linux certificates of IT expert Mirnes Glamočić', 
      'See the Linux certificates of professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/linux-certificates', 
      'https://mirnesglamocic.com/images/og_img/linux_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/linux_og.webp', 
      'certificates.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(14, 14, 'Portfolio of web design & web development projects by Mirnes Glamočić', 
      'View a portfolio of web design and web development projects by professional web developer and web designer Mirnes Glamočić from Bosnia and Herzegovina.', 
      'https://mirnesglamocic.com/projects', 
      'https://mirnesglamocic.com/images/og_img/Mirnes_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/MirnesGlamocic.webp', 
      'projects.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(15, 15, '403 Forbidden', 
      'Forbidden to view the site''s folders!', 
      'https://mirnesglamocic.com/forbidden', 
      'https://mirnesglamocic.com/images/og_img/frontend_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/frontend_og.webp', 
      'error.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50'),

(16, 16, '404 Not Found!', 
      'The requested URL was not found on this server!', 
      'https://mirnesglamocic.com/not-found', 
      'https://mirnesglamocic.com/images/og_img/404_og.jpg', 
      'https://mirnesglamocic.com/images/og_img/404_og.webp', 
      'error.min.css', 
      '2026-01-09 15:13:15', 
      '2026-01-09 15:14:50');
