-- =========================================
-- Inserts for table: certificates
-- Description: Image files for certificates
-- =========================================

-- First, clear the certificates table
TRUNCATE TABLE `certificates`;

INSERT INTO `certificates` (`certificate_id`, `picture`, `alt`, `skill`, `class`, `cert_desc_id`, `source`) VALUES
(1, 'Certificate-HTML-Essential-Training', 'Certificate HTML Essential Training', 'HTML WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(2, 'Certificate-Succeeding-in-Web-Development-Full-Stack-and-FrontEnd', 'Certificate Succeeding in Web Development Full Stack and FrontEnd', 'WebDevelopment', 'LinkedIn preview', 1, 'LinkedIn'),
(3, 'Certificate-HTML5-Geolocation', 'Certificate HTML5 Geolocation', 'HTML', 'LinkedIn preview', 1, 'LinkedIn'),
(4, 'Certificate-HTML-Tables', 'Certificate HTML Tables', 'HTML WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(5, 'Certificate-HTML-Structured-Semantic-Data', 'Certificate HTML Structured Semantic Data', 'HTML', 'LinkedIn preview', 1, 'LinkedIn'),
(6, 'Certificate-Learn-CSS', 'Certificate Learn CSS', 'FrontendIntro WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(7, 'Certificate-CSS-Animation', 'Certificate CSS Animation', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(8, 'Certificate-Tailwind-CSS-Essential-Training', 'Certificate Tailwind CSS Essential Training', 'Tailwind', 'LinkedIn preview', 1, 'LinkedIn'),
(9, 'Certificate-Advanced-CSS-Media-Queries', 'Certificate Advanced CSS Media Queries', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(10, 'Certificate-CSS-Images', 'Certificate CSS Images', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(11, 'Certificate-Making-Sense-of-the-CSS-Box-Model', 'Certificate Making Sense of the CSS Box Model', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(12, 'Certificate-CSS-Print-Style-Sheets', 'Certificate CSS Print Style Sheets', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(13, 'Certificate-CSS-Selectors', 'Certificate CSS Selectors', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(14, 'Certificate-Advanced-Responsive-Layouts-with-CSS-Flexbox', 'Certificate Advanced Responsive Layouts with CSS Flexbox', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(15, 'Certificate-CSS-Advanced-Layouts-with-Grid', 'Certificate CSS Advanced Layouts with Grid', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(16, 'Certificate-CSS-Scrolling-and-Parallax', 'Certificate CSS Scrolling and Parallax', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(17, 'Certificate-CSS-Layouts-From-Float-to-Flexbox-and-Grid', 'Certificate CSS Layouts From Float to Flexbox and Grid', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(18, 'Certificate-HTML-and-CSS-Linking', 'Certificate HTML and CSS Linking', 'HTMLandCSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(19, 'Certificate-CSS-Design-Systems-and-Architectures', 'Certificate CSS Design Systems and Architectures', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(20, 'Certificate-Advance-Your-Skills-in-HTML', 'Certificate Advance Your Skills in HTML', 'Frontend WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(21, 'Certificate-Building-a-Resilient-Web', 'Certificate Building a Resilient Web', 'WebDevelopment', 'LinkedIn preview', 1, 'LinkedIn'),
(22, 'Certificate-Building-Great-Forms', 'Certificate Building Great Forms', 'HTMLandCSS', 'LinkedIn preview', 1, 'LinkedIn'),
(23, 'Certificate-Explore-a-Career-in-FrontEnd-Web-Development', 'Certificate Explore a Career in FrontEnd Web Development', 'FrontendIntro UX WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(24, 'Certificate-CSS-Display', 'Certificate CSS Display', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(25, 'Certificate-CSS-Variable-Fonts', 'Certificate CSS Variable Fonts', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(26, 'Certificate-HTML-and-CSS-Creating-Navigation-Bars', 'Certificate HTML and CSS Creating Navigation Bars', 'HTMLandCSS', 'LinkedIn preview', 1, 'LinkedIn'),
(27, 'Certificate-CSS-Transforms-and-Transitions', 'Certificate CSS Transforms and Transitions', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(28, 'Certificate-CSS-Enhancing-Interfaces-with-Animation', 'Certificate CSS Enhancing Interfaces with Animation', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(29, 'Certificate-HTML-CSS-Creating-Forms', 'Certificate HTML CSS Creating Forms', 'HTMLandCSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(30, 'Certificate-CSS-to-Sass-Converting-an-Existing-Site', 'Certificate CSS to Sass Converting an Existing Site', 'SASS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(31, 'Certificate-Sass-Essential-Training', 'Certificate Sass Essential Training', 'SASS', 'LinkedIn preview', 1, 'LinkedIn'),
(32, 'Certificate-HTML-Metadata-in-the-Head', 'Certificate HTML Metadata in the Head', 'HTML WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(33, 'Certificate-Crafting-Meaningful-HTML', 'Certificate Crafting Meaningful HTML', 'HTML WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(34, 'Certificate-HTML-Images-and-Figures', 'Certificate HTML Images and Figures', 'HTML WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(35, 'Certificate-CSS-Variables-and-Fluid-Layouts', 'Certificate CSS Variables and Fluid Layouts', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(36, 'Certificate-Semantic-HTML-and-CSS-Code-Challenges', 'Certificate Semantic HTML and CSS Code Challenges', 'HTMLandCSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(37, 'Certificate-Design-the-Web-HTML-Background-Video', 'Certificate Design the Web HTML Background Video', 'HTML WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(38, 'Certificate-Learning-Web-Audio-and-Video', 'Certificate Learning Web Audio and Video', 'WebDevelopment WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(39, 'Certificate-Bootstrap-3-Essential-Training', 'Certificate Bootstrap 3 Essential Training', 'Bootstrap', 'LinkedIn preview', 1, 'LinkedIn'),
(40, 'Certificate-Bootstrap-4-Essential-Training', 'Certificate Bootstrap 4 Essential Training', 'Bootstrap', 'LinkedIn preview', 1, 'LinkedIn'),
(41, 'Certificate-Bootstrap-4-Layouts-Responsive-SinglePage-Design', 'Certificate Bootstrap 4 Layouts Responsive SinglePage Design', 'Bootstrap WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(42, 'Certificate-Bootstrap-4-with-Sass', 'Certificate Bootstrap 4 with Sass', 'Bootstrap', 'LinkedIn preview', 1, 'LinkedIn'),
(43, 'Certificate-Bootstrap-5-Essential-Training', 'Certificate Bootstrap 5 Essential Training', 'Bootstrap', 'LinkedIn preview', 1, 'LinkedIn'),
(44, 'Certificate-Code-Clinic-JavaScript', 'Certificate Code Clinic JavaScript', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(45, 'Certificate-Explore-Web-Development-with-Vanilla-JavaScript', 'Certificate Explore Web Development with Vanilla JavaScript', 'FrontendIntro', 'LinkedIn preview', 1, 'LinkedIn'),
(46, 'Certificate-Advance-Your-Skills-in-JavaScript', 'Certificate Advance Your Skills in JavaScript', 'Frontend', 'LinkedIn preview', 1, 'LinkedIn'),
(47, 'Certificate-Improve-Your-JavaScript-Language-Skills', 'Certificate Improve Your JavaScript Language Skills', 'Frontend', 'LinkedIn preview', 1, 'LinkedIn'),
(48, 'Certificate-Master-JavaScript', 'Certificate Master JavaScript', 'Frontend', 'LinkedIn preview', 1, 'LinkedIn'),
(49, 'Certificate-JavaScript-Patterns', 'Certificate JavaScript Patterns', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(50, 'Certificate-JavaScript-Arrays', 'Certificate JavaScript Arrays', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(51, 'Certificate-JavaScript-Best-Practices-for-Data', 'Certificate JavaScript Best Practices for Data', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(52, 'Certificate-JavaScript-Best-Practices-for-Functions-and-Classes', 'Certificate JavaScript Best Practices for Functions and Classes', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(53, 'Certificate-JavaScript-Essential-Training', 'Certificate JavaScript Essential Training', 'JavaScript', 'LinkedIn preview',1, 'LinkedIn'),
(54, 'Certificate-JavaScript-Classes', 'Certificate JavaScript Classes', 'JavaScript', 'LinkedIn preview',1, 'LinkedIn'),
(55, 'Certificate-Learning-JavaScript-Debugging', 'Certificate Learning JavaScript Debugging', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(56, 'Certificate-JavaScript-Web-Form-Programming', 'Certificate JavaScript Web Form Programming', 'JavaScript WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(57, 'Certificate-JavaScript-Code-Challenges', 'Certificate JavaScript Code Challenges', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(58, 'Certificate-JavaScript-Scope', 'Certificate JavaScript Scope', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(59, 'Certificate-JavaScript-Recursion', 'Certificate JavaScript Recursion', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(60, 'Certificate-JavaScript-Enhancing-the-DOM', 'Certificate JavaScript Enhancing the DOM', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(61, 'Certificate-JavaScript-Prototypes', 'Certificate JavaScript Prototypes', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(62, 'Certificate-Learning-ECMAScript-6-ES6', 'Certificate Learning ECMAScript 6 ES6', 'JavaScript', 'LinkedIn preview',1, 'LinkedIn'),
(63, 'Certificate-Vanilla-JavaScript-Service-Workers', 'Certificate Vanilla JavaScript Service Workers ES6', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(64, 'Certificate-Vanilla-JavaScript-Progressive-Web-Applications', 'Certificate Vanilla JavaScript Progressive Web Applications', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(65, 'Certificate-JavaScript-Closures', 'Certificate JavaScript Closures', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(66, 'Certificate-JavaScript-Modern-Browser-APIs', 'Certificate JavaScript Modern Browser APIs', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(67, 'Certificate-JavaScript-and-AJAX-Integration-Techniques', 'Certificate JavaScript and AJAX Integration Techniques', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(68, 'Certificate-JavaScript-Security-Essentials', 'Certificate JavaScript Security Essentials', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(69, 'Certificate-JavaScript-Async', 'Certificate JavaScript Async', 'JavaScript', 'LinkedIn preview',1, 'LinkedIn'),
(70, 'Certificate-Learning-Functional-Programming-with-JavaScript-ES6', 'Certificate Learning Functional Programming with JavaScript ES6', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(71, 'Certificate-JavaScript-Best-Practices-for-Code-Formatting', 'Certificate JavaScript Best Practices for Code Formatting', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(72, 'Certificate-Learning-App-Building-with-Vanilla-JavaScript', 'Certificate Learning App Building with Vanilla JavaScript', 'JavaScript', 'LinkedIn preview',1, 'LinkedIn'),
(73, 'Certificate-JavaScript-TestDriven-Development-ES6', 'Certificate JavaScript TestDriven Development ES6', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(74, 'Certificate-Web-Portfolio-Projects-Binding-and-Propagation', 'Certificate Web Portfolio Projects Binding and Propagation', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(75, 'Certificate-Vanilla-JavaScript-Ajax-and-Fetch', 'Certificate Vanilla JavaScript Ajax and Fetch', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(76, 'Certificate-JavaScript-for-Web-Designers', 'Certificate JavaScript for Web Designers', 'JavaScript WebDesigners', 'LinkedIn preview', 1, 'LinkedIn'),
(77, 'Certificate-Ethical-Hacking-with-JavaScript', 'Certificate Ethical Hacking with JavaScript', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(78, 'Certificate-ESLint-Integrating-with-Your-Workflow', 'Certificate ESLint Integrating with Your Workflow', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(79, 'Certificate-ESLint-Checking-for-Syntax-and-Logic-Errors', 'Certificate ESLint Checking for Syntax and Logic Errors', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(80, 'Certificate-ESLint-Customizing-Styles', 'Certificate ESLint Customizing Styles', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(81, 'Certificate-EndtoEnd-JavaScript-Testing-with-Cypress.io', 'Certificate EndtoEnd JavaScript Testing with Cypress.io', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(82, 'Certificate-TypeScript-ObjectOriented-Programming', 'Certificate TypeScript ObjectOriented Programming', 'TypeScript', 'LinkedIn preview', 1, 'LinkedIn'),
(83, 'Certificate-TypeScript-Upgrades-and-Features', 'Certificate TypeScript Upgrades and Features', 'TypeScript', 'LinkedIn preview', 1, 'LinkedIn'),
(84, 'Certificate-Explore-React.js-Development', 'Certificate Explore React.js Development', 'FrontendIntro', 'LinkedIn preview', 1, 'LinkedIn'),
(85, 'Certificate-jQuery-Essential-Training', 'Certificate jQuery Essential Training', 'jQuery', 'LinkedIn preview', 1, 'LinkedIn'),
(86, 'Certificate-jQuery-UI-Widgets', 'Certificate jQuery UI Widgets', 'jQuery', 'LinkedIn preview', 1, 'LinkedIn'),
(87, 'Certificate-jQuery-Mobile-Essential-Training', 'Certificate jQuery Mobile Essential Training', 'jQuery', 'LinkedIn preview', 1, 'LinkedIn'),
(88, 'Certificate-jQuery-for-Web-Designers', 'Certificate jQuery for Web Designers', 'jQuery WebDesigners', 'LinkedIn preview', 1, 'LinkedIn'),
(89, 'Certificate-Angular-Animations', 'Certificate Angular Animations', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(90, 'Certificate-Learning-Angular', 'Certificate Learning Angular ', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(91, 'Certificate-Learning-AngularJS-1', 'Certificate Learning AngularJS 1', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(92, 'Certificate-AngularJS-1.x-Tips-and-Tricks', 'Certificate AngularJS 1.x Tips and Tricks', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(93, 'Certificate-Angular-API-Communication-and-Authentication', 'Certificate Angular API Communication and Authentication', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(94, 'Certificate-Angular-Ecosystems', 'Certificate Angular Ecosystems', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(95, 'Certificate-Angular-Essential-Training', 'Certificate Angular Essential Training', 'Angular', 'LinkedIn preview',1, 'LinkedIn'),
(96, 'Certificate-Angular-Maintaining-Applications', 'Certificate Angular Maintaining Applications', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(97, 'Certificate-Angular-Testing-and-Debugging', 'Certificate Angular Testing and Debugging', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(98, 'Certificate-AngularJS-1-Adding-Registration-to-Your-Application', 'Certificate AngularJS 1 Adding Registration to Your Application', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(99, 'Certificate-AngularJS-1-Building-a-DataDriven-App', 'Certificate AngularJS 1 Building a DataDriven App', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(100, 'Certificate-AngularJS-1-Form-Validation', 'Certificate AngularJS 1 Form Validation', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),

(101, 'Certificate-AngularJS-Scope-and-Digest', 'Certificate AngularJS Scope and Digest', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(102, 'Certificate-Explore-Web-Development-with-Angular', 'Certificate Explore Web Development with Angular', 'FrontendIntro', 'LinkedIn preview', 1, 'LinkedIn'),
(103, 'Certificate-Learning-the-Angular-CLI', 'Certificate Learning the Angular CLI', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(104, 'Certificate-Upgrading-to-Angular-1.6', 'Certificate Upgrading to Angular 1.6', 'Angular', 'LinkedIn preview', 1, 'LinkedIn'),
(105, 'Certificate-React.js-Building-an-Interface', 'Certificate React.js Building an Interface', 'React', 'LinkedIn preview', 1, 'LinkedIn'),
(106, 'Certificate-React-Hooks', 'Certificate React Hooks', 'React', 'LinkedIn preview', 1, 'LinkedIn'),
(107, 'Certificate-React-Accessibility', 'Certificate React Accessibility', 'React', 'LinkedIn preview', 1, 'LinkedIn'),
(108, 'Certificate-React-Building-Progressive-Web-Apps-PWAs', 'Certificate React Building Progressive Web Apps PWAs', 'React', 'LinkedIn preview', 1, 'LinkedIn'),
(109, 'Certificate-React-Components-Context-and-Accessibility', 'Certificate React Components Context and Accessibility', 'React', 'LinkedIn preview', 1, 'LinkedIn'),
(110, 'Certificate-React-Ecosystems', 'Certificate React Ecosystems', 'React', 'LinkedIn preview', 1, 'LinkedIn'),
(111, 'Certificate-React-for-Web-Designers', 'Certificate React for Web Designers', 'React WebDesigners', 'LinkedIn preview', 1, 'LinkedIn'),
(112, 'Certificate-TypeScript-Essential-Training', 'Certificate TypeScript Essential Training', 'TypeScript', 'LinkedIn preview', 1, 'LinkedIn'),
(113, 'Certificate-JavaScript-Functions', 'Certificate JavaScript Functions', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(114, 'Certificate-Building-Great-Forms-with-HTML-and-CSS', 'Certificate Building Great Forms with HTML and CSS', 'HTMLandCSS', 'LinkedIn preview', 1, 'LinkedIn'),
(115, 'Certificate-Get-Ahead-in-PHP-PHP-7-Features-and-Frameworks', 'Certificate Get Ahead in PHP PHP 7 Features and Frameworks', 'BackendPHP', 'LinkedIn', 2, 'LinkedIn'),
(116, 'Certificate-Advanced-PHP', 'Certificate Advanced PHP', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(117, 'Certificate-Advanced-PHP-Debugging-Techniques', 'Certificate Advanced PHP Debugging Techniques', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(118, 'Certificate-PHP-Essential-Training', 'Certificate PHP Essential Training', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(119, 'Certificate-PHP-Tips-Tricks-and-Techniques', 'Certificate PHP Tips Tricks and Techniques', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(120, 'Certificate-Advanced-SQL-Logical-Query-Processing-Part-2', 'Certificate Advanced SQL Logical Query Processing Part 2', 'SQL', 'LinkedIn', 3, 'LinkedIn'),
(121, 'Certificate-React.js-Essential-Training', 'Certificate React.js Essential Training', 'React', 'LinkedIn preview', 1, 'LinkedIn'),
(122, 'Certificate-PHP-TestDriven-Development-with-PHPUnit', 'Certificate PHP TestDriven Development with PHPUnit', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(123, 'Certificate-PHP-for-WordPress', 'Certificate PHP for WordPress', 'WordPress PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(124, 'Certificate-PHP-for-Web-Designers', 'Certificate PHP for Web Designers', 'PHP WebDesigners', 'LinkedIn preview', 1, 'LinkedIn'),
(125, 'Certificate-PHP-Clean-URLs-on-Apache-Server', 'Certificate PHP Clean URLs on Apache Server', 'PHP SEO', 'LinkedIn preview', 2, 'LinkedIn'),
(126, 'Certificate-PHP-Email-with-Swift-Mailer', 'Certificate PHP Email with Swift Mailer', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(127, 'Certificate-PHP-Exporting-Data-to-Files', 'Certificate PHP Exporting Data to Files', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(128, 'Certificate-PHP-Design-Patterns', 'Certificate PHP Design Patterns', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(129, 'Certificate-PHP-Creating-Secure-Websites', 'Certificate PHP Creating Secure Websites', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(130, 'Certificate-PHP-Resizing-and-Watermarking-Images', 'Certificate PHP Resizing and Watermarking Images', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(131, 'Certificate-PHP-7-New-Features', 'Certificate PHP 7 New Features', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(132, 'Certificate-Learning-PHP', 'Certificate Learning PHP', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(133, 'Certificate-Learning-phpMyAdmin', 'Certificate Learning phpMyAdmin', 'PHP MySQL', 'LinkedIn preview', 2, 'LinkedIn'),
(134, 'Certificate-PHP-ObjectOriented-Programming', 'Certificate PHP ObjectOriented Programming', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(135, 'Certificate-Learning-Composer-the-PHP-Dependency-Manager', 'Certificate Learning Composer the PHP Dependency Manager', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(136, 'Certificate-Learning-Symfony-3', 'Certificate Learning Symfony 3', 'PHPFrameworks', 'LinkedIn preview', 2, 'LinkedIn'),
(137, 'Certificate-Learning-Symfony-4', 'Certificate Learning Symfony 4', 'PHPFrameworks', 'LinkedIn preview', 2, 'LinkedIn'),
(138, 'Certificate-First-Look-PHP-7.4', 'Certificate First Look PHP-7.4.', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(139, 'Certificate-Ajax-with-PHP-Add-Dynamic-Content-to-Websites', 'Certificate Ajax with PHP Add Dynamic Content to Websites', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(140, 'Certificate-PHP-with-MySQL-Essential-Training-1-The-Basics', 'Certificate PHP with MySQL Essential Training 1 The-Basics', 'PHP MySQL', 'LinkedIn preview', 2, 'LinkedIn'),
(141, 'Certificate-PHP-with-MySQL-Essential-Training-2-Build-a-CMS', 'Certificate PHP with MySQL Essential Training 2 Build a CMS', 'PHP MySQL', 'LinkedIn preview', 2, 'LinkedIn'),
(142, 'Certificate-PHP-ObjectOriented-Programming-with-Databases', 'Certificate PHP ObjectOriented Programming with Databases', 'PHP', 'LinkedIn preview', 2, 'LinkedIn'),
(143, 'Certificate-Advance-your-Skills-as-a-PHP-Developer-Core-PHP', 'Certificate Advance your Skills as a PHP Developer Core PHP', 'BackendPHP', 'LinkedIn', 2, 'LinkedIn'),
(144, 'Certificate-Advance-your-Skills-as-a-PHP-Developer-Testing-and-Debugging', 'Certificate Advance your Skills as a PHP Developer Testing and Debugging', 'BackendPHP', 'LinkedIn', 2, 'LinkedIn'),
(145, 'Certificate-Become-a-PHP-Developer', 'Certificate Become a PHP Developer', 'BackendIntro', 'LinkedIn', 2, 'LinkedIn'),
(146, 'Certificate-MVC-Frameworks-for-Building-PHP-Web-Applications', 'Certificate MVC Frameworks for Building PHP Web Applications', 'PHPFrameworks', 'LinkedIn preview', 2, 'LinkedIn'),
(147, 'Certificate-JavaScript-Promises-and-Async-Programming', 'Certificate JavaScript Promises and Async Programming', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(148, 'Certificate-Rapid-ES6-Training', 'Certificate Rapid ES6 Training', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(149, 'Certificate-Rapid-JavaScript-Training', 'Certificate Rapid JavaScript Training', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(150, 'Certificate-Reasoning-About-Asynchronous-JavaScript', 'Certificate Reasoning About Asynchronous JavaScript', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(151, 'Certificate-Good-Parts-of-JavaScript-and-the-Web', 'Certificate Good Parts of JavaScript and the Web', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(152, 'Certificate-JavaScript-Generators-and-Iterators', 'Certificate JavaScript Generators and Iterators', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(153, 'Certificate-JavaScript-Variables-and-Types', 'Certificate JavaScript Variables and Types', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(154, 'Certificate-Modern-Asynchronous-JavaScript', 'Certificate Modern Asynchronous JavaScript', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(155, 'Certificate-Hands-on-JavaScript-Project-JSON', 'Certificate Hands on JavaScript Project JSON', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(156, 'Certificate-JavaScript-Arrays-and-Collection', 'Certificate JavaScript Arrays and Collection', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(157, 'Certificate-JavaScript-Functions-Pluralsight', 'Certificate JavaScript Functions', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(158, 'Certificate-JavaScript-Module-Fundamentals', 'Certificate JavaScript Module Fundamentals', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(159, 'Certificate-JavaScript-Objects,Prototypes,andClasses', 'Certificate JavaScript Objects, Prototypes, and Classes', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(160, 'Certificate-JavaScript-Syntax-and-Operators', 'Certificate JavaScript Syntax and Operators', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(161, 'Certificate-Working-with-JavaScript-Modules', 'Certificate Working with JavaScript Modules', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(162, 'Certificate-Fixing-Common-JavaScript-Bugs', 'Certificate Fixing Common JavaScript Bugs', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(163, 'Certificate-Getting-Started-with-ES2017-ES8', 'Certificate Getting Started with ES2017 ES8', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(164, 'Certificate-JavaScript-Fundamentals-for-ES6', 'Certificate JavaScript Fundamentals for ES6', 'JavaScript', 'Pluralsight preview', 1, 'Pluralsight'),
(165, 'Certificate-Event-Handling-in-jQuery', 'Certificate Event Handling in jQuery', 'jQuery', 'Pluralsight preview', 1, 'Pluralsight'),
(166, 'Certificate-Fixing-Common-jQuery-Bugs', 'Certificate Fixing Common jQuery Bugs', 'jQuery', 'Pluralsight preview', 1, 'Pluralsight'),
(167, 'Certificate-jQuery-Advanced-Topics', 'Certificate jQuery Advanced Topics', 'jQuery', 'Pluralsight preview', 1, 'Pluralsight'),
(168, 'Certificate-jQuery-Forms-and-Bootstrap-3', 'Certificate jQuery Forms and Bootstrap 3', 'jQuery', 'Pluralsight preview', 1, 'Pluralsight'),
(169, 'Certificate-jQuery-3-The-Big-Picture', 'Certificate jQuery 3 The Big Picture', 'jQuery', 'Pluralsight preview', 1, 'Pluralsight'),
(170, 'Certificate-Interacting-with-data-using-jQuery-3-and-Ajax', 'Certificate Interacting with data using jQuery3 and Ajax', 'jQuery', 'Pluralsight preview', 1, 'Pluralsight'),
(171, 'Certificate-8-Things-You-Must-Know-in-Python', 'Certificate 8 Things You Must Know in Python', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(172, 'Certificate-Advance-Your-Skills-in-Python', 'Certificate Advance Your Skills in Python', 'BackendPython', 'LinkedIn', 2, 'LinkedIn'),
(173, 'Certificate-Advanced-Python', 'Certificate Advanced Python', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(174, 'Certificate-Become-a-Python-Developer', 'Certificate Become a Python Developer', 'BackendIntro', 'LinkedIn', 2, 'LinkedIn'),
(175, 'Certificate-Learning-Python', 'Certificate Learning Python', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(176, 'Certificate-Learning-the-Python-3-Standard-Library', 'Certificate Learning the Python 3 Standard Library', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(177, 'Certificate-Python-Advanced-Design-Patterns', 'Certificate Python Advanced Design Patterns', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(178, 'Certificate-Python-Automation-and-Testing', 'Certificate Python Automation and Testing', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(179, 'Certificate-Python-Code-Challenges', 'Certificate Python Code Challenges', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(180, 'Certificate-Python-Data-Structures-and-Algorithms', 'Certificate Python Data Structures and Algorithms', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(181, 'Certificate-Python-Design-Patterns', 'Certificate Python Design Patterns', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(182, 'Certificate-Python-Essential-Training', 'Certificate Python Essential Training', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(183, 'Certificate-Python-GUI-Development-with-Tkinter', 'Certificate Python GUI Development with Tkinter', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(184, 'Certificate-Python-ObjectOriented-Programming', 'Certificate Python ObjectOriented Programming', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(185, 'Certificate-Python-Projects', 'Certificate Python Projects', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(186, 'Certificate-Web-Scraping-with-Python', 'Certificate Web Scraping with Python', 'Python', 'LinkedIn preview', 2, 'LinkedIn'),
(187, 'Certificate-Building-a-Website-with-Node.js-and-Express.js', 'Certificate Building a Website with Node.js and Express.js', 'Node', 'LinkedIn preview', 2, 'LinkedIn'),
(188, 'Certificate-Building-RESTful-APIs-with-Node.js-and-Express', 'Certificate Building RESTful APIs with Node.js and Express', 'Node', 'LinkedIn preview', 2, 'LinkedIn'),
(189, 'Certificate-Learning-npm-the-Node-Package-Manager', 'Certificate Learning npm the Node Package Manager', 'Node', 'LinkedIn preview', 2, 'LinkedIn'),
(190, 'Certificate-Learning-the-JavaScript-Language', 'Certificate Learning the JavaScript Language', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(191, 'Certificate-Node.js-RealTime-Web-with-Socket.IO', 'Certificate Node.js RealTime Web with Socket.IO', 'Node', 'LinkedIn preview', 2, 'LinkedIn'),
(192, 'Certificate-Node.js-Securing-RESTful-APIs', 'Certificate Node.js Securing RESTful APIs', 'Node', 'LinkedIn preview', 2, 'LinkedIn'),
(193, 'Certificate-Node.js-Security', 'Certificate Node.js Security', 'Node', 'LinkedIn preview', 2, 'LinkedIn'),
(194, 'Certificate-Node.js-Essential-Training', 'Certificate Node.js Essential Training', 'Node', 'LinkedIn preview', 2, 'LinkedIn'),
(195, 'Certificate-React-Creating-and-Hosting-a-FullStack-Site', 'Certificate React Creating and Hosting a FullStack Site', 'React', 'LinkedIn preview', 1, 'LinkedIn'),
(196, 'Certificate-TypeScript-for-Node.js-Developers', 'Certificate TypeScript for Node.js Developers', 'TypeScript', 'LinkedIn preview', 1, 'LinkedIn'),
(197, 'Certificate-Advanced-SQL-Window-Functions', 'Certificate Advanced SQL Window Functions', 'SQL', 'LinkedIn', 3, 'LinkedIn'),
(198, 'Certificate-Advanced-SQL-Logical-Query-Processing-Part-1', 'Certificate Advanced SQL Logical Query Processing Part 1', 'SQL', 'LinkedIn', 3, 'LinkedIn'),
(199, 'Certificate-Explore-a-Career-in-Database-Development', 'Certificate Explore a Career in Database Development', 'Database', 'LinkedIn', 3, 'LinkedIn'),
(200, 'Certificate-Node.js-Modules-and-Packages', 'Certificate Node.js Modules and Packages', 'Node', 'LinkedIn preview', 2, 'LinkedIn'),
(201, 'Certificate-First-Look-MySQL-8-for-Developers', 'Certificate First Look MySQL 8 for Developers', 'MySQL', 'LinkedIn preview', 3, 'LinkedIn'),
(202, 'Certificate-MySQL-Advanced-Topics', 'Certificate MySQL Advanced Topics', 'MySQL', 'LinkedIn preview', 3, 'LinkedIn'),
(203, 'Certificate-MySQL-Essential-Training', 'Certificate MySQL Essential Training', 'MySQL', 'LinkedIn preview', 3, 'LinkedIn'),
(204, 'Certificate-MySQL-for-Advanced-Analytics-Tips-Tricks-Techniques', 'Certificate MySQL for Advanced Analytics Tips Tricks Techniques', 'MySQL', 'LinkedIn preview', 3, 'LinkedIn'),
(205, 'Certificate-SQL-Essential-Training', 'Certificate SQL Essential Training', 'SQL', 'LinkedIn', 3, 'LinkedIn'),
(206, 'Certificate-SQL-for-Data-Analysis', 'Certificate SQL for Data Analysis', 'SQL', 'LinkedIn', 3, 'LinkedIn'),
(207, 'Certificate-SQL-Queries-Made-Easy', 'Certificate SQL Queries Made Easy', 'SQL', 'LinkedIn', 3, 'LinkedIn'),
(208, 'Certificate-SQL-Tips-and-Tricks-for-Data-Science', 'Certificate SQL Tips and Tricks for Data Science', 'SQL', 'LinkedIn', 3, 'LinkedIn'),
(209, 'Certificate-Advanced-MySQL-and-MariaDB', 'Certificate Advanced MySQL and MariaDB', 'MySQL', 'LinkedIn preview', 3, 'LinkedIn'),
(210, 'Certificate-MySQL-Installation-and-Configuration', 'Certificate MySQL Installation and Configuration', 'MySQL', 'LinkedIn preview', 3, 'LinkedIn'),
(211, 'Certificate-Improve-Your-Web-Design-Coding-Skills', 'Certificate Improve Your Web Design Coding Skills', 'Frontend WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(212, 'Certificate-Close-Encounters-with-PHP', 'Certificate Close Encounters with PHP', 'PHP', 'Pluralsight preview', 2, 'Pluralsight'),
(213, 'Certificate-Cookies-and-Sessions-in-PHP', 'Certificate Cookies and Sessions in PHP', 'PHP', 'Pluralsight preview', 2, 'Pluralsight'),
(214, 'Certificate-ObjectOrientedPHP-Classical-Inheritance', 'Certificate Object Oriented PHP Classical Inheritance', 'PHP', 'Pluralsight preview', 2, 'Pluralsight'),
(215, 'Certificate-ObjectOrientedPHP-Essential-Construct', 'Certificate Object Oriented PHP Essential Construct', 'PHP', 'Pluralsight preview', 2, 'Pluralsight'),
(216, 'Certificate-PHP-Design-Patterns-Pluralsight', 'Certificate PHP Design Patterns', 'PHP', 'Pluralsight preview', 2, 'Pluralsight'),
(217, 'Certificate-PHP-predefined-variables', 'Certificate PHP predefined variables', 'PHP', 'Pluralsight preview', 2, 'Pluralsight'),
(218, 'Certificate-PHP-Web-Application-Security', 'Certificate PHP Web Application Security', 'PHP', 'Pluralsight preview', 2, 'Pluralsight'),
(219, 'Certificate-What-is-new-in-PHP7', 'Certificate What is new in PHP7', 'PHP', 'Pluralsight preview', 2, 'Pluralsight'),
(220, 'Certificate-CSS-SoloLearn', 'Certificate CSS Tutorial', 'Frontend', 'SoloLearn', 1, 'SoloLearn'),
(221, 'Certificate-HTML-SoloLearn', 'Certificate HTML SoloLearn', 'Frontend', 'SoloLearn', 1, 'SoloLearn'),
(222, 'Certificate-JavaScript-SoloLearn', 'Certificate JavaScript SoloLearn', 'Frontend', 'SoloLearn', 1, 'SoloLearn'),
(223, 'Certificate-jQuery-SoloLearn', 'Certificate jQuery SoloLearn', 'Frontend', 'SoloLearn', 1, 'SoloLearn'),
(224, 'Certificate-Building-a-Headless-WordPress-App-with-REST-API', 'Certificate Building a Headless WordPress App with REST-API', 'WordPress Rest', 'LinkedIn', 4, 'LinkedIn'),
(225, 'Certificate-Building-a-Small-Business-Website-with-WordPress', 'Certificate Building a Small Business Website with WordPress', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(226, 'Certificate-Building-a-WordPress-Membership-Site-with-Ecommerce', 'Certificate Building a WordPress Membership Site with Ecommerce', 'WordPressEcommerce', 'LinkedIn preview', 4, 'LinkedIn'),
(227, 'Certificate-Creating-Block-Patterns-in-WordPress', 'Certificate Creating Block Patterns in WordPress', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(228, 'Certificate-First-Look-WordPress-FullSite-Editing', 'Certificate First Look WordPress Full Site Editing', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(229, 'Certificate-Installing-and-Running-WordPress-Local-by-FlyWheel', 'Certificate Installing and Running WordPress Local by FlyWheel', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(230, 'Certificate-Installing-and-Running-WordPress-Shared-Hosting', 'Certificate Installing and Running WordPress Shared Hosting', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(231, 'Certificate-Learning-Genesis-for-WordPress', 'Certificate Learning Genesis for WordPress', 'WordPressTheme', 'LinkedIn preview', 4, 'LinkedIn'),
(232, 'Certificate-Using-Custom-Meta-Boxes-in-WordPress', 'Certificate Using Custom Meta Boxes in WordPress', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(233, 'Certificate-WordPress-5-Essential-Training', 'Certificate WordPress 5 Essential Training', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(234, 'Certificate-WordPress-5-Essential-Training-Site-Administration', 'Certificate WordPress 5 Essential Training Site Administration', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(235, 'Certificate-WordPress-Accessibility', 'Certificate WordPress Accessibility', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(236, 'Certificate-WordPress-Action-and-Filter-Hooks', 'Certificate WordPress Action and Filter Hooks', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(237, 'Certificate-WordPress-Advanced-Custom-Fields', 'Certificate WordPress Advanced Custom Fields', 'WordPressPlugin', 'LinkedIn', 4, 'LinkedIn'),
(238, 'Certificate-WordPress-Backing-Up-Your-Site', 'Certificate WordPress Backing Up Your Site', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(239, 'Certificate-WordPress-Building-a-Secure-Site', 'Certificate WordPress Building a Secure Site', 'WordPressEcommerce', 'LinkedIn preview', 4, 'LinkedIn'),
(240, 'Certificate-WordPress-Building-Child-Themes', 'Certificate WordPress Building Child Themes', 'WordPressTheme', 'LinkedIn preview', 4, 'LinkedIn'),
(241, 'Certificate-WordPress-Contact-Forms', 'Certificate WordPress Contact Forms', 'WordPressPlugin', 'LinkedIn', 4, 'LinkedIn'),
(242, 'Certificate-WordPress-Content-Blocks-Working-with-Themes', 'Certificate WordPress Content Blocks Working with Themes', 'WordPressTheme', 'LinkedIn preview', 4, 'LinkedIn'),
(243, 'Certificate-WordPress-Creating-an-Intranet-Website', 'Certificate WordPress Creating an Intranet Website', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(244, 'Certificate-WordPress-Custom-Post-Types-and-Taxonomies', 'Certificate WordPress Custom Post Types and Taxonomies', 'WordPressPlugin', 'LinkedIn', 4, 'LinkedIn'),
(245, 'Certificate-WordPress-Customizing-Themes-with-Genesis', 'Certificate WordPress Customizing Themes with Genesis', 'WordPressTheme', 'LinkedIn preview', 4, 'LinkedIn'),
(246, 'Certificate-WordPress-Customizing-WooCommerce-Themes', 'Certificate WordPress Customizing WooCommerce Themes', 'WordPressTheme', 'LinkedIn preview', 4, 'LinkedIn'),
(247, 'Certificate-WordPress-Developing-Blocks-with-Gutenberg', 'Certificate WordPress Developing Blocks with Gutenberg', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(248, 'Certificate-WordPress-Ecommerce', 'Certificate WordPress Ecommerce', 'WordPressEcommerce', 'LinkedIn preview', 4, 'LinkedIn'),
(249, 'Certificate-WordPress-Ecommerce-WooCommerce', 'Certificate WordPress Ecommerce WooCommerce', 'WordPressEcommerce', 'LinkedIn preview', 4, 'LinkedIn'),
(250, 'Certificate-WordPress-for-Education', 'Certificate WordPress for Education', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(251, 'Certificate-WordPress-Internationalization', 'Certificate WordPress Internationalization', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(252, 'Certificate-WordPress-Migration', 'Certificate WordPress Migration', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(253, 'Certificate-WordPress-Plugin-Development', 'Certificate WordPress Plugin Development', 'WordPressPlugin', 'LinkedIn', 4, 'LinkedIn'),
(254, 'Certificate-WordPress-REST-API', 'Certificate WordPress REST API', 'WordPress Rest', 'LinkedIn', 1, 'LinkedIn'),
(255, 'Certificate-WordPress-Speeding-Up-Your-Site', 'Certificate WordPress Speeding Up Your Site', 'WordPressEcommerce', 'LinkedIn preview', 4, 'LinkedIn'),
(256, 'Certificate-WordPress-Understanding-the-New-Paradigm', 'Certificate WordPress Understanding the New Paradigm', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(257, 'Certificate-WordPress-Using-a-Content-Delivery-Network', 'Certificate WordPress Using a Content Delivery Network', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(258, 'Certificate-WordPress-Workflows', 'Certificate WordPress Workflows', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(259, 'Certificate-WordPress-WPCLI', 'Certificate WordPress WPCLI', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(260, 'Certificate-Designing-RESTful-APIs', 'Certificate Designing RESTful APIs', 'WebServices', 'LinkedIn', 5, 'LinkedIn'),
(261, 'Certificate-API-Testing-and-Validation', 'Certificate API Testing and Validation', 'WebServices', 'LinkedIn', 5, 'LinkedIn'),
(262, 'Certificate-HTTP-Essential-Training', 'Certificate HTTP Essential Training', 'WebServices WebDesign', 'LinkedIn preview', 5, 'LinkedIn'),
(263, 'Certificate-Learning-REST-APIs', 'Certificate Learning REST APIs', 'WebServices', 'LinkedIn', 5, 'LinkedIn'),
(264, 'Certificate-Web-Security-OAuth-and-OpenID-Connect', 'Certificate Web Security OAuth and OpenID Connect', 'WebServices', 'LinkedIn', 5, 'LinkedIn'),
(265, 'Certificate-JavaScript-and-JSON-Integration-Techniques', 'Certificate JavaScript and JSON Integration Techniques', 'JavaScript JSON', 'LinkedIn preview', 5, 'LinkedIn'),
(266, 'Certificate-JSON-Essential-Training', 'Certificate JSON Essential Training', 'JSON XML', 'LinkedIn', 5, 'LinkedIn'),
(267, 'Certificate-Processing-and-Interchanging-JSON-Data', 'Certificate Processing and Interchanging JSON Data', 'JSON XML', 'LinkedIn', 5, 'LinkedIn'),
(268, 'Certificate-Learn-API-Documentation-with-JSON-and-XML', 'Certificate Learn API Documentation with JSON and XML', 'JSON XML', 'LinkedIn', 5, 'LinkedIn'),
(269, 'Certificate-XML-Essential-Training', 'Certificate XML Essential Training', 'JSON XML', 'LinkedIn', 5, 'LinkedIn'),
(270, 'Certificate-International-SEO', 'Certificate International SEO', 'SEO', 'LinkedIn', 8, 'LinkedIn'),
(271, 'Certificate-Learning-Local-SEO', 'Certificate Learning Local SEO', 'SEO', 'LinkedIn', 8, 'LinkedIn'),
(272, 'Certificate-SEO-Ecommerce-Strategies', 'Certificate SEO Ecommerce Strategies', 'SEO', 'LinkedIn', 8, 'LinkedIn'),
(273, 'Certificate-SEO-Keyword-Strategy', 'Certificate SEO Keyword Strategy', 'SEO', 'LinkedIn', 8, 'LinkedIn'),
(274, 'Certificate-SEO-Link-Building', 'Certificate SEO Link Building', 'SEO', 'LinkedIn', 8, 'LinkedIn'),
(275, 'Certificate-SEO-Optimize-Your-Social-Media-Profiles', 'Certificate SEO Optimize Your Social Media Profiles', 'SEO', 'LinkedIn', 8, 'LinkedIn'),
(276, 'Certificate-SEO-Videos', 'Certificate SEO Videos', 'SEO', 'LinkedIn', 8, 'LinkedIn'),
(277, 'Certificate-Technical-SEO', 'Certificate Technical SEO', 'SEO', 'LinkedIn', 8, 'LinkedIn'),
(278, 'Certificate-WordPress-SEO', 'Certificate WordPress SEO', 'WordPress SEO', 'LinkedIn', 8, 'LinkedIn'),
(279, 'Certificate-Advance-Your-Skills-in-UX-Design', 'Certificate Advance Your Skills in UX Design', 'UX Path', 'LinkedIn', 7, 'LinkedIn'),
(280, 'Certificate-Become-a-User-Experience-Designer', 'Certificate Become a User Experience Designer', 'UX Intro WebDesign', 'LinkedIn', 7, 'LinkedIn'),
(281, 'Certificate-Become-an-Interaction-Designer', 'Certificate Become an Interaction Designer', 'UX Intro', 'LinkedIn', 7, 'LinkedIn'),
(282, 'Certificate-Design-Powered-by-Data-Getting-Started-with-UX-Web-Analytics', 'Certificate Design Powered by Data Getting Started with UX Web Analytics', 'UX', 'LinkedIn preview', 7, 'LinkedIn'),
(283, 'Certificate-Empathy-in-UX-Design', 'Certificate Empathy in UX Design', 'UX', 'LinkedIn preview', 7, 'LinkedIn'),
(284, 'Certificate-Figma-for-UX-Desig', 'Certificate Figma for UX Design', 'UX', 'LinkedIn preview', 7, 'LinkedIn'),
(285, 'Certificate-Improve-Your-UX-Design-Skills', 'Certificate Improve Your UX Design Skills', 'UX Path', 'LinkedIn', 7, 'LinkedIn'),
(286, 'Certificate-Interaction-Design-Dashboards-and-Visualization', 'Certificate Interaction Design Dashboards and Visualization', 'Interaction Design', 'LinkedIn preview', 7, 'LinkedIn'),
(287, 'Certificate-Interaction-Design-Design-Patterns-as-Building-Blocks', 'Certificate Interaction Design Design Patterns as Building Blocks', 'Interaction Design', 'LinkedIn preview', 7, 'LinkedIn'),
(288, 'Certificate-Interaction-Design-Flow', 'Certificate Interaction Design Flow', 'Interaction Design', 'LinkedIn preview', 7, 'LinkedIn'),
(289, 'Certificate-Interaction-Design-for-Ecommerce', 'Certificate Interaction Design for Ecommerce', 'Interaction Design', 'LinkedIn preview', 7, 'LinkedIn'),
(290, 'Certificate-Interaction-Design-for-the-Web', 'Certificate Interaction Design for the Web', 'Interaction Design', 'LinkedIn preview', 7, 'LinkedIn'),
(291, 'Certificate-Interaction-Design-Interface', 'Certificate Interaction Design Interface', 'Interaction Design', 'LinkedIn preview', 7, 'LinkedIn'),
(292, 'Certificate-Interaction-Design-Projects-and-Platforms', 'Certificate Interaction Design Projects and Platforms', 'Interaction Design', 'LinkedIn preview', 7, 'LinkedIn'),
(293, 'Certificate-Interaction-Design-Software-and-Web-Design-Patterns', 'Certificate Interaction Design Software and Web Design Patterns', 'Interaction Design', 'LinkedIn preview', 7, 'LinkedIn'),
(294, 'Certificate-Interaction-Design-Structure', 'Certificate Interaction Design Structure', 'Interaction Design', 'LinkedIn preview', 7, 'LinkedIn'),
(295, 'Certificate-Miro-for-UX-Brainstorming-and-Collaboration', 'Certificate Miro for UX Brainstorming and Collaboration', 'UX', 'LinkedIn preview', 7, 'LinkedIn'),
(296, 'Certificate-Sketching-for-UX-Designers', 'Certificate Sketching for UX Designers', 'UX', 'LinkedIn preview', 7, 'LinkedIn'),
(297, 'Certificate-Surveys-and-Questionnaires-for-UX-Projects', 'Certificate Surveys and Questionnaires for UX Projects', 'UX', 'LinkedIn preview', 7, 'LinkedIn'),
(298, 'Certificate-User-Experience-for-Web-Design', 'Certificate User Experience for Web Design', 'UX Web Design', 'LinkedIn preview', 7, 'LinkedIn'),
(299, 'Certificate-UX-Deep-Dive-Analyzing-Data', 'Certificate UX Deep Dive Analyzing Data', 'UX', 'LinkedIn preview', 7, 'LinkedIn'),
(300, 'Certificate-UX-Deep-Dive-Mapping', 'Certificate UX Deep Dive Mapping', 'UX', 'LinkedIn preview', 7, 'LinkedIn'),


(301, 'Certificate-UX-Deep-Dive-Remote-Research', 'Certificate UX Deep Dive Remote Research', 'UX', 'LinkedIn preview', 7, 'LinkedIn'),
(302, 'Certificate-UX-Deep-Dive-Usability-Testing', 'Certificate UX Deep Dive Usability Testing', 'UX', 'LinkedIn preview', 7, 'LinkedIn'),
(303, 'Certificate-UX-Design-for-Developers', 'Certificate UX Design for Developers', 'UX', 'LinkedIn preview', 7, 'LinkedIn'),
(304, 'Certificate-UX-for-Web-Forms', 'Certificate UX for Web Forms', 'UX', 'LinkedIn preview', 7, 'LinkedIn'),
(305, 'Certificate-UX-Foundations-Accessibility', 'Certificate UX Foundations Accessibility', 'UX Foundations', 'LinkedIn preview', 7, 'LinkedIn'),
(306, 'Certificate-UX-Foundations-Content-Strategy', 'Certificate UX Foundations Content Strategy', 'UX Foundations', 'LinkedIn preview', 7, 'LinkedIn'),
(307, 'Certificate-UX-Foundations-Generational-Design', 'Certificate UX Foundations Generational Design', 'UX Foundations', 'LinkedIn preview', 7, 'LinkedIn'),
(308, 'Certificate-UX-Foundations-Interaction-Design', 'Certificate UX Foundations Interaction Design', 'UX Foundations', 'LinkedIn preview', 7, 'LinkedIn'),
(309, 'Certificate-UX-Foundations-Logic-and-Content', 'Certificate UX Foundations Logic and Content', 'UX Foundations', 'LinkedIn preview', 7, 'LinkedIn'),
(310, 'Certificate-UX-Foundations-Storytelling', 'Certificate UX Foundations Storytelling', 'UX Foundations', 'LinkedIn preview', 7, 'LinkedIn'),
(311, 'Certificate-UX-Foundations-Usability-Testing', 'Certificate UX Foundations Usability Testing', 'UX Foundations', 'LinkedIn preview', 7, 'LinkedIn'),
(312, 'Certificate-UX-Design-1-Overview', 'Certificate UX Design 1 Overview', 'UX Parts', 'LinkedIn preview', 7, 'LinkedIn'),
(313, 'Certificate-UX-Design-2-Analyzing-User-Data', 'Certificate UX Design 2 Analyzing User Data', 'UX Parts', 'LinkedIn preview', 7, 'LinkedIn'),
(314, 'Certificate-UX-Design-3-Creating-Personas', 'Certificate UX-Design 3 Creating Personas', 'UX Parts', 'LinkedIn preview', 7, 'LinkedIn'),
(315, 'Certificate-UX-Design-4-Ideation', 'Certificate UX Design 4 Ideation', 'UX Parts', 'LinkedIn preview', 7, 'LinkedIn'),
(316, 'Certificate-UX-Design-5-Creating-Scenarios-and-Storyboards', 'Certificate UX Design 5 Creating Scenarios and Storyboards', 'UX Parts', 'LinkedIn preview', 7, 'LinkedIn'),
(317, 'Certificate-UX-Design-6-Paper-Prototyping', 'Certificate UX Design 6 Paper Prototyping', 'UX Parts', 'LinkedIn preview', 7, 'LinkedIn'),
(318, 'Certificate-UX-Design-7-Implementation-Planning', 'Certificate UX Design 7 Implementation Planning', 'UX Parts', 'LinkedIn preview', 7, 'LinkedIn'),
(319, 'Certificate-Advanced-Photoshop-Curves', 'Certificate Advanced Photoshop Curves', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(320, 'Certificate-Changing-a-Sky-Background-in-Photoshop', 'Certificate Changing a Sky Background in Photoshop', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(321, 'Certificate-Changing-a-Studio-Background-in-Photoshop', 'Certificate Changing a Studio Background in Photoshop', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(322, 'Certificate-Designing-Websites-from-Photoshop-to-Dreamweaver', 'Certificate Designing Websites from Photoshop to Dreamweaver', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(323, 'Certificate-Learning-Photoshop-Portrait-Retouching', 'Certificate Learning Photoshop Portrait Retouching', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(324, 'Certificate-Mastering-Selections-in-Photoshop-CC', 'Certificate Mastering Selections in Photoshop CC', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(325, 'Certificate-Modular-UX-Design-with-Photoshop', 'Certificate Modular UX Design with Photoshop', 'Photoshop UX', 'LinkedIn preview', 9, 'LinkedIn'),
(326, 'Certificate-Photographing-for-Compositing-in-Photoshop', 'Certificate Photographing for Compositing in Photoshop', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(327, 'Certificate-Photoshop-Advanced-Adjustment-Layer-and-Blend-Modes', 'Certificate Photoshop Advanced Adjustment Layer and Blend Modes', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(328, 'Certificate-Photoshop-Automation-Tips-Tricks-and-Techniques', 'Certificate Photoshop Automation Tips Tricks and Techniques', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(329, 'Certificate-Photoshop-Backgrounds-and-Textures', 'Certificate Photoshop Backgrounds and Textures', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(330, 'Certificate-Photoshop-Channels-and-Masks', 'Certificate Photoshop Channels and Masks', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(331, 'Certificate-Photoshop-Compositing-Tips-Tricks-Techniques', 'Certificate Photoshop Compositing Tips Tricks Techniques', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(332, 'Certificate-Photoshop-Customizing-Brushes', 'Certificate Photoshop Customizing Brushes', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(333, 'Certificate-Photoshop-for-Teaching-and-Learning', 'Certificate Photoshop for Teaching and Learning', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(334, 'Certificate-Photoshop-Natural-Media-Painting', 'Certificate Photoshop Natural Media Painting', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(335, 'Certificate-Photoshop-Pastel-Drawing', 'Certificate Photoshop Pastel Drawing', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(336, 'Certificate-Photoshop-Quick-Tips', 'Certificate Photoshop Quick Tips', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(337, 'Certificate-Photoshop-Selections-Tips-Tricks-and-Techniques', 'Certificate Photoshop Selections Tips Tricks and Techniques', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(338, 'Certificate-Photoshop-Smart-Objects', 'Certificate Photoshop Smart Objects', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(339, 'Certificate-Photoshop-Tips-Tricks-Techniques', 'Certificate Photoshop Tips Tricks Techniques', 'Photoshop', 'LinkedIn', 9, 'LinkedIn'),
(340, 'Certificate-Photoshop-for-Designers-Color', 'Certificate Photoshop for Designers Color', 'Photoshop Design', 'LinkedIn preview', 9, 'LinkedIn'),
(341, 'Certificate-Photoshop-for-Designers-Designing-with-Grids-and-Guides', 'Certificate Photoshop for Designers Designing with Grids and Guides', 'Photoshop Design', 'LinkedIn preview', 9, 'LinkedIn'),
(342, 'Certificate-Photoshop-for-Designers-Filters', 'Certificate Photoshop for Designers Filters', 'Photoshop Design', 'LinkedIn preview', 9, 'LinkedIn'),
(343, 'Certificate-Photoshop-for-Designers-Textures', 'Certificate Photoshop for Designers Textures', 'Photoshop Design', 'LinkedIn preview', 9, 'LinkedIn'),
(344, 'Certificate-Photoshop-for-Designers-Type-Essentials', 'Certificate Photoshop for Designers Type Essentials', 'Photoshop Design', 'LinkedIn preview', 9, 'LinkedIn'),
(345, 'Certificate-Photoshop-for-Designers-Working-with-Bridge', 'Certificate Photoshop for Designers Working with Bridge', 'Photoshop Design', 'LinkedIn preview', 9, 'LinkedIn'),
(346, 'Certificate-Photoshop-for-Designers-Working-with-Shapes', 'Certificate Photoshop for Designers Working with Shapes', 'Photoshop Design', 'LinkedIn preview', 9, 'LinkedIn'),
(347, 'Certificate-Photoshop-for-UX-Design', 'Certificate Photoshop for UX Design', 'Photoshop UX', 'LinkedIn preview', 9, 'LinkedIn'),
(348, 'Certificate-Photoshop-for-Web-Design', 'Certificate Photoshop for Web Design', 'Photoshop Web Design', 'LinkedIn', 9, 'LinkedIn'),
(349, 'Certificate-Learning-Lightroom-Classic', 'Certificate Learning Lightroom Classic', 'Lightroom', 'LinkedIn preview', 9, 'LinkedIn'),
(350, 'Certificate-Lightroom-Classic-CC-and-Photoshop-Workflows-Start-to-Finish-Studies', 'Certificate Lightroom Classic CC and Photoshop Workflows Start to Finish Studies', 'Lightroom', 'LinkedIn preview', 9, 'LinkedIn'),
(351, 'Certificate-Lightroom-Classic-CC-Presets-Bundle', 'Certificate Lightroom Classic CC Presets Bundle', 'Lightroom', 'LinkedIn preview', 9, 'LinkedIn'),
(352, 'Certificate-Lightroom-Classic-Essential-Training', 'Certificate Lightroom Classic Essential Training', 'Lightroom', 'LinkedIn preview', 9, 'LinkedIn'),
(353, 'Certificate-Become-a-Software-Developer', 'Certificate Become a Software Developer', 'FrontendIntro WebDesign', 'LinkedIn preview', 6, 'LinkedIn'),
(354, 'Certificate-Master-Photoshop-for-Web-Design', 'Certificate Master Photoshop for Web Design', 'WebDesignPath', 'LinkedIn', 6, 'LinkedIn'),
(355, 'Certificate-CSS-Essential-Training', 'Certificate CSS Essential Training', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(356, 'Certificate-Design-Aesthetics-for-the-Web', 'Certificate Design Aesthetics for the Web', 'WebDesign', 'LinkedIn preview', 6, 'LinkedIn'),
(357, 'Certificate-Emmet-Fast-and-Efficient-Web-Coding', 'Certificate Emmet Fast and Efficient Web Coding', 'WebDevelopment WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(358, 'Certificate-Mapping-the-Modern-Web-Design-Process', 'Certificate Mapping the Modern Web Design Process', 'WebDesign', 'LinkedIn preview', 6, 'LinkedIn'),
(359, 'Certificate-Responsive-Layout', 'Certificate Responsive Layout', 'CSS WebDesign', 'LinkedIn preview', 6, 'LinkedIn'),
(360, 'Certificate-AWK-Essential-Training', 'Certificate AWK Essential Training', 'Editors', 'LinkedIn preview', 1, 'LinkedIn'),
(361, 'Certificate-AWK-Essential-Training-NASBA', 'Certificate AWK Essential Training NASBA', 'Editors', 'LinkedIn preview', 1, 'LinkedIn'),
(362, 'Certificate-Bash-Patterns-and-Regular-Expressions', 'Certificate Bash Patterns and Regular Expressions', 'Bash', 'LinkedIn preview', 1, 'LinkedIn'),
(363, 'Certificate-Learning-Bash-Scripting', 'Certificate Learning Bash Scripting', 'Bash', 'LinkedIn preview', 1, 'LinkedIn'),
(364, 'Certificate-Choosing-a-Linux-Distribution', 'Certificate Choosing a Linux Distribution', 'LinuxDistro', 'LinkedIn preview', 1, 'LinkedIn'),
(365, 'Certificate-Learning-Linux-Command-Line', 'Certificate Learning Linux Command Line', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(366, 'Certificate-Learning-Linux-Shell-Scripting', 'Certificate Learning Linux Shell Scripting', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(367, 'Certificate-Learning-nano', 'Certificate Learning nano', 'Editors', 'LinkedIn preview', 1, 'LinkedIn'),
(368, 'Certificate-Learning-Ubuntu-Desktop', 'Certificate Learning Ubuntu Desktop', 'LinuxDistro', 'LinkedIn preview', 1, 'LinkedIn'),
(369, 'Certificate-Learning-Vim', 'Certificate Learning Vim', 'Editors', 'LinkedIn preview', 1, 'LinkedIn'),
(370, 'Certificate-Linux-Files-and-Permissions', 'Certificate Linux Files and Permissions', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(371, 'Certificate-Linux-Foundation-Cert-Prep-Operation-of-Running-Systems-Ubuntu', 'Certificate Linux Foundation CertPrep Operation of Running Systems Ubuntu', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(372, 'Certificate-Linux-Foundation-Cert-Prep-Network-Security-Ubuntu', 'Certificate Linux Foundation Cert Prep Network Security Ubuntu', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(373, 'Certificate-Practice-It-SQL-Joins', 'Certificate Practice It SQL Joins', 'SQL', 'LinkedIn', 3, 'LinkedIn'),
(374, 'Certificate-Linux-Foundation-Cert-Prep-HTTP-Services-Ubuntu', 'Certificate Linux Foundation Cert Prep HTTP Services Ubuntu', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(375, 'Certificate-Linux-Foundation-Cert-Prep-HTTP-Services-Ubuntu-NASBA', 'Certificate Linux Foundation Cert Prep HTTP Services Ubuntu NASBA', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(376, 'Certificate-Linux-Foundation-Cert-Prep-Network-Filesystems-and-File-Services-Ubuntu', 'Certificate Linux Foundation Cert Prep Network Filesystems and File Services Ubuntu', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(377, 'Certificate-Linux-Foundation-Cert-Prep-Network-Security-Ubuntu-NASBA', 'Certificate Linux Foundation Cert Prep Network Security Ubuntu NASBA', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(378, 'Certificate-Learning-CentOS-Linux', 'Certificate Learning CentOS Linux', 'LinuxDistro', 'LinkedIn preview', 1, 'LinkedIn'),
(379, 'Certificate-PHP-Techniques-Pagination', 'Certificate PHP Techniques Pagination', 'PHP', 'LinkedIn preview', 1, 'LinkedIn'),
(380, 'Certificate-Linux-Foundation-Cert-Prep-Email-Services-Ubuntu', 'Certificate Linux Foundation Cert Prep Email Services Ubuntu', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(381, 'Certificate-Linux-Foundation-Cert-Prep-Essential-Commands-Ubuntu', 'Certificate Linux Foundation Cert Prep Essential Commands Ubuntu', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(382, 'Certificate-Linux-Foundation-Cert-Prep-Networking-Ubuntu', 'Certificate Linux Foundation Cert Prep Networking Ubuntu', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(383, 'Certificate-Linux-Foundation-Cert-Prep-Service-Configuration-Ubuntu', 'Certificate Linux Foundation Cert Prep Service Configuration Ubuntu', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(384, 'Certificate-Linux-Foundation-Cert-Prep-Storage-Management-Ubuntu', 'Certificate Linux Foundation Cert Prep Storage Management Ubuntu', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(385, 'Certificate-Linux-Foundation-Cert-Prep-User-and-Group-Management-Ubuntu', 'Certificate Linux Foundation Cert Prep User and Group Management Ubuntu', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(386, 'Certificate-Linux-Foundation-Cert-Prep-Virtualization-Ubuntu', 'Certificate Linux Foundation Cert Prep Virtualization Ubuntu', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(387, 'Certificate-Linux-Overview-and-Installation', 'Certificate Linux Overview and Installation', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(388, 'Certificate-Linux-System-Maintenance', 'Certificate Linux System Maintenance', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(389, 'Certificate-Linux-System-Maintenance-COMPTIA', 'Certificate Linux System Maintenance COMPTIA', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(390, 'Certificate-SED-Essential-Training', 'Certificate SED Essential Training', 'Editors', 'LinkedIn preview', 1, 'LinkedIn'),
(391, 'Certificate-Unix-Essential-Training', 'Certificate Unix Essential Training', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(392, 'Certificate-Linux-Bash-Shell-and-Scripts', 'Certificate Linux Bash Shell and Scripts', 'Bash', 'LinkedIn preview', 1, 'LinkedIn'),
(393, 'Certificate-Learning-VirtualBox', 'Certificate Learning VirtualBox', 'LinuxDistro', 'LinkedIn preview', 1, 'LinkedIn'),
(394, 'Certificate-Troubleshooting-and-Debugging-Bash', 'Certificate Troubleshooting and Debugging Bash', 'Bash', 'LinkedIn preview', 1, 'LinkedIn'),
(395, 'Certificate-Learning-Debian-Linux', 'Certificate Learning Debian Linux', 'LinuxDistro', 'LinkedIn preview', 1, 'LinkedIn'),
(396, 'Certificate-Learning-Fedora-Linux', 'Certificate Learning Fedora Linux', 'LinuxDistro', 'LinkedIn preview', 1, 'LinkedIn'),
(397, 'Certificate-Create-a-Quick-Clean-and-Cheap-Website-with-Bootstrap-Templates', 'Certificate Create a Quick Clean and Cheap Website with Bootstrap Templates', 'Bootstrap', 'LinkedIn preview', 1, 'LinkedIn'),
(398, 'Certificate-Linux-Package-Managers-and-Repositories', 'Certificate Linux Package Managers and Repositories', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(399, 'Certificate-Linux-Kernels-and-Logging-for-System-Administration', 'Certificate Linux Kernels and Logging for System Administration', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(400, 'Certificate-Linux-System-Information-and-Directory-Structure-Tools-CPE', 'Certificate Linux System Information and Directory Structure Tools CPE', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),


(401, 'Certificate-Linux-System-Information-and-Directory-Structure-Tools', 'Certificate Linux System Information and Directory Structure Tools', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(402, 'Certificate-Linux-Multitasking-at-the-Command-Line', 'Certificate Linux Multitasking at the Command Line', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(403, 'Certificate-Linux-CentOS-7-Overview-and-Installation-COMPTIA', 'COMPTIA Certificate Linux CentOS 7 Overview and Installation', 'CentOS', 'LinkedIn preview', 1, 'LinkedIn'),
(404, 'Certificate-Linux-CentOS-7-Overview-and-Installation', 'Certificate Linux CentOS 7 Overview and Installation', 'CentOS', 'LinkedIn preview', 1, 'LinkedIn'),
(405, 'Certificate-Linux-CentOS-7-Overview-and-Installation-NASBA', 'NASBA Certificate Linux CentOS 7 Overview and Installation', 'CentOS', 'LinkedIn preview', 1, 'LinkedIn'),
(406, 'Certificate-Linux-Package-Management-for-CentOS', 'Certificate Linux Package Management for CentOS', 'CentOS', 'LinkedIn preview', 1, 'LinkedIn'),
(407, 'Certificate-Linux-Package-Management-for-CentOS-NASBA', 'Certificate Linux Package Management for CentOS NASBA', 'CentOS', 'LinkedIn preview', 1, 'LinkedIn'),
(408, 'Certificate-Linux-CentOS-7-Shells-and-Processes-NASBA', 'Certificate Linux CentOS 7 Shells and Processes NASBA', 'CentOS', 'LinkedIn preview', 1, 'LinkedIn'),
(409, 'Certificate-Linux-CentOS-7-Shells-and-Processes', 'Certificate Linux CentOS 7 Shells and Processes', 'CentOS', 'LinkedIn preview', 1, 'LinkedIn'),
(410, 'Certificate-Linux-for-PHP-Developers', 'Certificate Linux for PHP Developers', 'Linux PHP', 'LinkedIn preview', 1, 'LinkedIn'),
(411, 'Certificate-Linux-Foundation-Cert-Prep-Remote-Access-Ubuntu', 'Certificate Linux Foundation Cert Prep Remote Access Ubuntu', 'LinuxFoundation', 'LinkedIn preview', 1, 'LinkedIn'),
(412, 'Certificate-Linux-System-Engineer-Bash-Shell-Scripting-for-Automation', 'Certificate Linux System Engineer Bash Shell Scripting for Automation', 'LinuxEngineer', 'LinkedIn preview', 1, 'LinkedIn'),
(413, 'Certificate-Linux-System-Engineer-Networking-and-SSH-COMPTIA', 'COMPTIA Certificate Linux System Engineer Networking and SSH', 'LinuxEngineer', 'LinkedIn preview', 1, 'LinkedIn'),
(414, 'Certificate-Linux-System-Engineer-Networking-and-SSH', 'Certificate Linux System Engineer Networking and SSH', 'LinuxEngineer', 'LinkedIn preview', 1, 'LinkedIn'),
(415, 'Certificate-Linux-Firewalls-and-SELinux', 'Certificate Linux Firewalls and SELinux', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(416, 'Certificate-Linux-System-Engineer-Database-Servers-Using-MariaDB', 'Certificate Linux System Engineer Database Servers Using MariaDB', 'LinuxEngineer MariaDB', 'LinkedIn preview', 1, 'LinkedIn'),
(417, 'Certificate-Linux-CentOS-7-Files-and-Permissions', 'Certificate Linux CentOS 7 Files and Permissions', 'CentOS', 'LinkedIn preview', 1, 'LinkedIn'),
(418, 'Certificate-Linux-CentOS-7-Files-and-Permissions-NASBA', 'NASBA Certificate Linux CentOS 7 Files and Permissions', 'CentOS', 'LinkedIn preview', 1, 'LinkedIn'),
(419, 'Certificate-Linux-Network-Configuration', 'Certificate Linux Network Configuration', 'Linux', 'LinkedIn preview', 1, 'LinkedIn'),
(420, 'Certificate-Easy-PHP-Projects-SingleServing-Sites', 'Certificate Easy PHP Projects SingleServing Sites', 'PHP', 'LinkedIn preview', 1, 'LinkedIn'),
(421, 'Certificate-Tech-on-the-Go-History-of-PHP', 'Certificate Tech on the Go History of PHP', 'PHP', 'LinkedIn preview', 1, 'LinkedIn'),
(422, 'Certificate-PHP-Code-Challenges', 'Certificate PHP Code Challenges', 'PHP', 'LinkedIn preview', 1, 'LinkedIn'),
(423, 'Certificate-Processing-Data-Sources-in-PHP', 'Certificate Processing Data Sources in PHP', 'PHP', 'LinkedIn preview', 1, 'LinkedIn'),
(424, 'Certificate-Design-the-Web-Adding-Dynamic-QR-Codes', 'Certificate Design the Web Adding Dynamic QR Codes', 'PHP WebDesigners', 'LinkedIn preview', 1, 'LinkedIn'),
(425, 'Certificate-Responsive-Images', 'Certificate Responsive Images', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(426, 'Certificate-Responsive-Typography-Techniques', 'Certificate Responsive Typography Techniques', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(427, 'Certificate-SQL-Essential-Training-2023', 'Certificate SQL Essential Training', 'SQL', 'LinkedIn preview', 3, 'LinkedIn'),
(428, 'Certificate-8-Git-Commands-You-Should-Know', 'Certificate 8 Git Commands You Should Know', 'Git', 'LinkedIn preview', 1, 'LinkedIn'),
(429, 'Certificate-Git-Branches-Merges-and-Remotes', 'Certificate Git Branches Merges and Remotes', 'Git', 'LinkedIn preview', 1, 'LinkedIn'),
(430, 'Certificate-Git-Essential-Training-The-Basics-2019', 'Certificate Git Essential Training The Basics', 'Git', 'LinkedIn preview', 1, 'LinkedIn'),
(431, 'Certificate-Git-Intermediate-Techniques-2018', 'Certificate Git Intermediate Techniques', 'Git', 'LinkedIn preview', 1, 'LinkedIn'),
(432, 'Certificate-Git-Workflows', 'Certificate Git Workflows', 'Git', 'LinkedIn preview', 1, 'LinkedIn'),
(433, 'Certificate-GitHub-Essential-Training', 'Certificate GitHub Essential Training', 'GitHub', 'LinkedIn preview', 1, 'LinkedIn'),
(434, 'Certificate-Learning-Git-and-GitHub-2023', 'Certificate Learning Git and GitHub', 'GitHub', 'LinkedInNew preview', 10, 'LinkedIn'),
(435, 'Certificate-Learning-GitHub', 'Certificate Learning GitHub', 'GitHub', 'LinkedIn preview', 10, 'LinkedIn'),
(436, 'Certificate-Learning-Git-and-GitHub', 'Certificate Learning Git and GitHub', 'GitHub', 'LinkedIn preview', 10, 'LinkedIn'),
(437, 'Certificate-Learning-GitHub-Pages', 'Certificate Learning GitHub Pages', 'GitHub', 'LinkedIn preview', 10, 'LinkedIn'),
(438, 'Certificate-Learning-Software-Version-Control', 'Certificate Learning Software Version Control', 'VCS', 'LinkedIn preview', 1, 'LinkedIn'),
(439, 'Certificate-Version-Control-for-Everyone', 'Certificate Version Control for Everyone', 'VCS', 'LinkedIn preview', 1, 'LinkedIn'),
(440, 'Certificate-Data-Modeling-in-MongoDB', 'Certificate Data Modeling in MongoDB', 'MongoDB', 'LinkedIn preview', 1, 'LinkedIn'),
(441, 'Certificate-Database-Clinic-MongoDB', 'Certificate Database Clinic MongoDB', 'MongoDB', 'LinkedIn preview', 1, 'LinkedIn'),
(442, 'Certificate-MongoDB-Essential-Training', 'Certificate MongoDB Essential Training', 'MongoDB', 'LinkedIn preview', 1, 'LinkedIn'),
(443, 'Certificate-Learning-MongoDB', 'Certificate Learning MongoDB', 'MongoDB', 'LinkedIn preview', 1, 'LinkedIn'),
(444, 'Certificate-PostgreSQL-Essential-Training', 'Certificate PostgreSQL Essential Training', 'PostgreSQL', 'LinkedIn preview', 1, 'LinkedIn'),
(445, 'Certificate-PostgreSQL-Client-Applications', 'Certificate PostgreSQL Client Applications', 'PostgreSQL', 'LinkedIn preview', 1, 'LinkedIn'),
(446, 'Certificate-Learning-Docker', 'Certificate Learning Docker', 'Docker', 'LinkedIn', 1, 'LinkedIn'),
(447, 'Certificate-Docker-Essential-Training', 'Certificate Docker Essential Training', 'Docker', 'LinkedIn', 1, 'LinkedIn'),
(448, 'Certificate-Docker-for-Windows', 'Certificate Docker for Windows', 'Docker', 'LinkedIn', 1, 'LinkedIn'),
(449, 'Certificate-Git-from-Scratch', 'Certificate Git from Scratch', 'Git', 'LinkedIn', 1, 'LinkedIn'),
(450, 'Certificate-Accessibility-for-Web-Design', 'Certificate Accessibility for Web Design', 'WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(451, 'Certificate-Creating-a-Responsive-Web-Design', 'Certificate Creating a Responsive Web Design', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(452, 'Certificate-Creating-a-Responsive-Web-Design-Advanced-Techniques', 'Certificate Creating-a-Responsive Web Design Advanced Techniques', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(453, 'Certificate-Creating-a-Responsive-Web-Experience', 'Certificate Creating a Responsive Web Experience', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(454, 'Certificate-How-to-Plan-Your-Website', 'Certificate How to Plan Your Website', 'WebDevelopment', 'LinkedIn preview', 1, 'LinkedIn'),
(455, 'Certificate-Learning-Chrome-Web-Developer-Tools', 'Certificate Learning Chrome Web Developer Tools', 'ViewSource', 'LinkedIn preview', 1, 'LinkedIn'),
(456, 'Certificate-Learning-Responsive-Web-Design-in-the-Browser', 'Certificate Learning Responsive Web Design in the Browser', 'ViewSource', 'LinkedIn preview', 1, 'LinkedIn'),
(457, 'Certificate-Learning-Responsive-Media', 'Certificate Learning Responsive Media', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(458, 'Certificate-JavaScript-on-the-Go-Async', 'Certificate JavaScript on the Go Async', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(459, 'Certificate-JavaScript-Functions-2022', 'Certificate JavaScript Functions 2022', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(460, 'Certificate-Designing-Websites-for-Performance', 'Certificate Designing Websites for Performance', 'CSS WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(461, 'Certificate-JavaScript-as-a-Second-Language', 'Certificate JavaScript as a Second Language', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(462, 'Certificate-JavaScript-Events', 'Certificate JavaScript Events', 'JavaScript', 'LinkedIn preview', 1, 'LinkedIn'),
(463, 'Certificate-jQuery-Building-an-Interface', 'Certificate jQuery Building an Interface', 'jQuery', 'LinkedIn preview', 1, 'LinkedIn'),
(464, 'Certificate-Web-Design-Efficient-Workflow', 'Certificate Web Design Efficient Workflow', 'WebDesign', 'LinkedIn preview', 1, 'LinkedIn'),
(465, 'Certificate-Workflow-Tools-for-Web-Developers', 'Certificate Workflow Tools for Web Developers', 'WebDevelopment', 'LinkedIn preview', 1, 'LinkedIn'),
(466, 'Certificate-Learning-jQuery-UI', 'Certificate Learning jQuery UI', 'jQuery', 'LinkedIn preview', 1, 'LinkedIn'),
(467, 'Certificate-Learning-Regular-Expressions', 'Certificate Learning Regular Expressions', 'WebDevelopment', 'LinkedIn preview', 1, 'LinkedIn'),
(468, 'Certificate-Learning-Troubleshooting-for-Web-Developers', 'Certificate Learning Troubleshooting for Web Developers', 'ViewSource', 'LinkedIn preview', 1, 'LinkedIn'),
(469, 'Certificate-Learning-Web-Components', 'Certificate Learning Web Components', 'WebDevelopment', 'LinkedIn preview', 1, 'LinkedIn'),
(470, 'Certificate-Search-Techniques-for-Web-Developers', 'Certificate Search Techniques for Web Developers', 'WebDevelopment', 'LinkedIn preview', 1, 'LinkedIn'),
(471, 'Certificate-View-Source', 'Certificate View Source', 'ViewSource', 'LinkedIn preview', 1, 'LinkedIn'),
(472, 'Certificate-WordPress-Essential-Training-2022', 'Certificate WordPress Essential Training', 'WordPress', 'LinkedIn preview', 4, 'LinkedIn'),
(473, 'Certificate-WordPress-Everything-about-Plugins', 'Certificate WordPress Everything about Plugins', 'WordPressPlugin', 'LinkedIn', 4, 'LinkedIn'),
(474, 'Certificate-Learning-Elementor-for-WordPress-Design', 'LinkedIn Certificate Learning Elementor for WordPress Design', 'WordPressPlugin', 'LinkedIn', 4, 'LinkedIn'),
(475, 'Certificate-Troubleshoot-and-Repair-Your-WordPress-Website', 'LinkedIn Certificate Troubleshoot and Repair Your WordPress Website', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(476, 'Certificate-Project-Management-Tools-for-WordPress', 'LinkedIn Certificate Project Management Tools for WordPress', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(477, 'Certificate-WordPress-Staging-a-Site', 'LinkedIn Certificate WordPress Staging a Site', 'WordPress', 'LinkedIn', 4, 'LinkedIn'),
(478, 'Certificate-WordPress-SEO-2022', 'LinkedIn Certificate WordPress SEO 2022', 'WordPress SEO', 'LinkedIn', 4, 'LinkedIn'),
(479, 'Certificate-Nano-Tips-to-Use-and-Improve-SEO-with-Sam-Dey', 'LinkedIn Certificate Nano Tips to Use and Improve SEO with Sam Dey', 'SEO', 'LinkedIn', 8, 'LinkedIn'),
(480, 'Certificate-SEO-Foundations', 'LinkedIn Certificate SEO Foundations', 'SEO', 'LinkedIn', 8, 'LinkedIn'),
(481, 'Certificate-SEO-Keyword-Strategy-2022', 'LinkedIn Certificate SEO Keyword Strategy', 'SEO', 'LinkedIn', 8, 'LinkedIn'),
(482, 'Certificate-Danny-Sullivan-on-SEO', 'LinkedIn Certificate Danny Sullivan on SEO', 'SEO', 'LinkedIn', 1, 'LinkedIn'),
(483, 'Certificate-Improve-SEO-for-Your-Website', 'LinkedIn Certificate Improve SEO for Your Website', 'SEO', 'LinkedIn', 1, 'LinkedIn'),
(484, 'Certificate-Improve-SEO-for-Your-Website-NASBA', 'NASBA LinkedIn Certificate Improve SEO for Your Website', 'SEO', 'LinkedIn', 1, 'LinkedIn'),
(485, 'Certificate-Marketing-Strategy-SEO-Content-Writing', 'LinkedIn Certificate Marketing Strategy SEO Content Writing', 'SEO', 'LinkedIn', 1, 'LinkedIn'),
(486, 'Certificate-Nano-Tips-for-Ranking-a-Website-in-Google-with-Sam-Dey', 'LinkedIn Certificate Nano Tips for Ranking a Website in Google with Sam Dey', 'SEO', 'LinkedIn', 1, 'LinkedIn'),
(487, 'Certificate-SEO-Strategy-Link-Building', 'LinkedIn Certificate SEO Strategy Link Building', 'SEO', 'LinkedIn', 1, 'LinkedIn'),
(488, 'Certificate-Technical-WordPress-SEO', 'LinkedIn Certificate Technical WordPress SEO', 'WordPress SEO', 'LinkedIn', 1, 'LinkedIn'),
(489, 'Certificate-Learning-GitHub-2023', 'Certificate Learning GitHub', 'GitHub', 'LinkedInNew preview', 10, 'LinkedIn'),
(490, 'Certificate-Git-Essential-Training', 'Certificate Git Essential Training', 'Git', 'LinkedInNew preview', 10, 'LinkedIn'),
(491, 'Certificate-Learning-Software-Version-Control-2023', 'Certificate Learning Software Version Control', 'VCS', 'LinkedInNew preview', 10, 'LinkedIn'),
(492, 'Certificate-Coding-Exercises-CSS-Logical-Properties', 'Certificate Coding Exercises CSS Logical Properties', 'CSS', 'LinkedInNew preview', 1, 'LinkedIn'),
(493, 'Certificate-CSS-Combining-Grid-and-Flexbox', 'Certificate CSS Combining Grid and Flexbox', 'CSS', 'LinkedInNew preview', 1, 'LinkedIn'),
(494, 'Certificate-CSS-Essential-Training-2023', 'Certificate CSS Essential Training', 'CSS', 'LinkedInNew preview', 1, 'LinkedIn'),
(495, 'Certificate-CSS-Inheritance-Specificity-and-the-Cascade', 'Certificate CSS Inheritance Specificity and the Cascade', 'CSS', 'LinkedInNew preview', 1, 'LinkedIn'),
(496, 'Certificate-Level-Up-CSS-Layout', 'Certificate Level Up CSS Layout', 'CSS', 'LinkedInNew preview', 1, 'LinkedIn'),
(497, 'Certificate-Practice-It-CSS-Layout', 'Certificate Practice It CSS Layout', 'CSS', 'LinkedInNew preview', 1, 'LinkedIn'),
(498, 'Certificate-Creating-Icon-Fonts-for-the-Web', 'Certificate Creating Icon Fonts for the Web', 'SVG', 'LinkedInNew preview', 1, 'LinkedIn'),
(499, 'Certificate-Learning-SVG', 'Certificate Learning SVG', 'SVG', 'LinkedInNew preview', 1, 'LinkedIn'),
(500, 'Certificate-Creating-Web-Icons-with-SVG', 'Certificate Creating Web Icons with SVG', 'SVG', 'LinkedInNew preview', 1, 'LinkedIn'),


(501, 'Certificate-Design-the-Web-SVG-Rollovers-with-CSS', 'Certificate Design the Web SVG Rollovers with CSS', 'SVG', 'LinkedInNew preview', 1, 'LinkedIn'),
(502, 'Certificate-Design-the-Web-Using-Symbols-in-SVG', 'Certificate Design the Web Using Symbols in SVG', 'SVG', 'LinkedInNew preview', 1, 'LinkedIn'),
(503, 'Certificate-Illustrator-CC-for-Web-Design-SVG', 'Certificate Illustrator CC for Web Design SVG', 'SVG', 'LinkedInNew preview', 1, 'LinkedIn'),
(504, 'Certificate-GitHub-Quick-Tips', 'Certificate GitHub Quick Tips', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(505, 'Certificate-GitHub-Codespaces-for-Students', 'Certificate GitHub Codespaces for Students', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(506, 'Certificate-Docker-Your-First-Project', 'Certificate Docker Your First Project', 'Docker', 'LinkedIn', 1, 'LinkedIn'),
(507, 'Certificate-Learning-Docker-Compose', 'Certificate Learning Docker Compose', 'Docker', 'LinkedIn', 1, 'LinkedIn'),
(508, 'Certificate-GitHub-Essential-Training-1-The-Basics', 'Certificate GitHub Essential Training 1-The Basics', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(509, 'Certificate-Learning-GitHub-Actions', 'Certificate Learning GitHub Actions', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(510, 'Certificate-Advanced-GitHub-Actions', 'Certificate Advanced GitHub Actions', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(511, 'Certificate-GitHub-Actions-for-CICD', 'Certificate GitHub Actions for CICD', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(512, 'Certificate-Learning-GitHub-Packages', 'Certificate Learning GitHub Packages', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(513, 'Certificate-8-Git-Commands-You-Should-Know-2024', 'Certificate 8 Git Commands You Should Know', 'Git', 'LinkedInNew preview', 1, 'LinkedIn'),
(514, 'Certificate-Complete-Guide-to-Git', 'Certificate Complete Guide to Git', 'Git', 'LinkedInNew preview', 1, 'LinkedIn'),
(515, 'Certificate-Ditch-Your-Git-GUI-Customize-Terminal', 'Certificate Ditch Your Git GUI Customize Terminal', 'Git', 'LinkedInNew preview', 1, 'LinkedIn'),
(516, 'Certificate-Git-Intermediate-Techniques', 'Certificate Git Intermediate Techniques', 'Git', 'LinkedInNew preview', 1, 'LinkedIn'),
(517, 'Certificate-GitHub-Issues-and-Projects-for-Teams', 'Certificate GitHub Issues and Projects for Teams', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(518, 'Certificate-Practical-GitHub-Actions', 'Certificate Practical GitHub Actions', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(519, 'Certificate-GitHub-Foundations-Privacy-Security-and-Administration', 'Certificate GitHub Foundations Privacy Security and Administration', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(520, 'Certificate-Practical-GitHub-Copilot', 'Certificate Practical GitHub Copilot', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(521, 'Certificate-25-GitHub-Configuration-Files-You-Should-Be-Using', 'Certificate 25 GitHub Configuration Files You Should Be Using', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(522, 'Certificate-Practical-GitHub-Project-Management-and-Collaboration-PMI', 'PMI Certificate Practical GitHub Project Management and Collaboration', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(523, 'Certificate-Practical-GitHub-Project-Management-and-Collaboration', 'Certificate Practical GitHub Project Management and Collaboration', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(524, 'Certificate-GitHub-Advanced-Security-GHAS', 'Certificate GitHub Advanced Security GHAS', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn'),
(525, 'Certificate-Benefits-of-GitHub-Community', 'Certificate Benefits of GitHub Community', 'GitHub', 'LinkedInNew preview', 1, 'LinkedIn');
